//! F6 — can pure-Rust resvg replace the `rsvg-convert` subprocess?
//!
//! Two questions, deliberately separate:
//!
//! 1. **Fidelity.** Feed *the same SVG string* (generated by the python-chess
//!    that ships today) to both rasterisers and diff the pixels. This isolates
//!    "is resvg a faithful rasteriser" from "is my port of `chess.svg.board()`
//!    faithful", which is R7 and a different experiment.
//! 2. **The seam rule.** `chess.svg.board` is a 390-unit square, so a square
//!    edge lands on an exact pixel only at multiples of 390/15 = 26. The Python
//!    measured eight stray pixels per scanline at 1152 and zero at 1144. If
//!    resvg does not reproduce that, `snap26` is either unnecessary or wrong,
//!    and either way the layout arithmetic changes.

use anyhow::{Context, Result, bail};
use std::io::Write;
use std::path::Path;
use std::process::{Command, Stdio};

/// The picture's own colours. Deliberately lichess's, not gruvbox: the point of
/// a real image is that it is the board from the website. Mirrors
/// `scripts/dash/sixel.py::COLOURS`.
const SQ_LIGHT: [u8; 3] = [0xf0, 0xd9, 0xb5];
const SQ_DARK: [u8; 3] = [0xb5, 0x88, 0x63];

/// `390 / 15` — see the module docs and `sixel.py::GRID_PX`.
const GRID_PX: u32 = 26;

pub fn run(_args: &[String]) -> Result<()> {
    let mut report = String::new();
    macro_rules! say {
        ($($t:tt)*) => {{ let l = format!($($t)*); println!("{l}"); report.push_str(&l); report.push('\n'); }};
    }

    say!("## F6 — resvg vs rsvg-convert, and the seam rule\n");

    let have_rsvg = which("rsvg-convert");
    if !have_rsvg {
        say!("`rsvg-convert` absent; fidelity half of F6 skipped, seam half still valid.");
    }

    // Positions chosen to exercise the parts of the SVG that differ: an empty
    // board (seam counting needs no pieces in the way), the start position (all
    // twelve glyphs at once), a midgame from a real game, a last-move highlight
    // (a different square colour pair), and a king in check (the ring).
    let cases: &[(&str, &str, Option<&str>, bool)] = &[
        ("empty", "8/8/8/8/8/8/8/8 w - - 0 1", None, false),
        (
            "start",
            "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
            None,
            false,
        ),
        (
            "midgame",
            "r5k1/1b1rp2p/p4pp1/1p6/1P2P3/P1N2P2/2P3PP/1R1R2K1 b - - 2 24",
            Some("b5b4"),
            false,
        ),
        (
            "check-flipped",
            "rnb1kbnr/pppp1ppp/8/4p3/6Pq/5P2/PPPPP2P/RNBQKBNR w KQkq - 1 3",
            Some("d8h4"),
            true,
        ),
    ];

    // ---- fidelity, at the snapped size the dashboard actually uses ----
    let px = 1144u32;
    say!("### Fidelity at {px}px (same SVG into both rasterisers)\n");
    say!("| case | max channel delta | pixels differing >2/255 | verdict |");
    say!("|---|---|---|---|");
    let mut worst_frac = 0.0f64;
    for (name, fen, last, flip) in cases {
        let svg = board_svg(fen, *last, *flip, px)?;
        let ours = render_resvg(&svg, px).context("resvg render")?;
        if !have_rsvg {
            continue;
        }
        let theirs = render_rsvg(&svg, px).context("rsvg-convert render")?;
        if ours.len() != theirs.len() {
            bail!(
                "{name}: size mismatch, resvg {} bytes vs rsvg {} bytes",
                ours.len(),
                theirs.len()
            );
        }
        let mut max_delta = 0u8;
        let mut differing = 0usize;
        for (a, b) in ours.chunks_exact(4).zip(theirs.chunks_exact(4)) {
            // Compare RGB only. Both paths produce an opaque board; alpha
            // differences in the last row of margin are not interesting.
            let d = (0..3).map(|i| a[i].abs_diff(b[i])).max().unwrap();
            max_delta = max_delta.max(d);
            if d > 2 {
                differing += 1;
            }
        }
        let total = ours.len() / 4;
        let frac = differing as f64 / total as f64;
        worst_frac = worst_frac.max(frac);
        say!(
            "| {name} | {max_delta} | {differing} ({:.4}%) | {} |",
            frac * 100.0,
            if frac < 0.001 { "PASS" } else { "INSPECT" }
        );
    }
    if have_rsvg {
        say!(
            "\nWorst differing fraction: {:.4}%. Threshold for R6 is 0.1%.\n",
            worst_frac * 100.0
        );
    }

    // ---- the seam rule ----
    say!("### The seam rule (empty board, interior scanline)\n");
    say!("Counting pixels on a mid-board scanline that are neither square colour.");
    say!("Python measured 8/line at 1152 and 0 at 1144 through rsvg.\n");
    say!("| size | mod 26 | resvg strays | rsvg strays |");
    say!("|---|---|---|---|");
    let (_, empty_fen, _, _) = cases[0];
    for size in [1144u32, 1152, 1170, 1180, 1196] {
        let svg = board_svg(empty_fen, None, false, size)?;
        let ours = seam_count(&render_resvg(&svg, size)?, size);
        let theirs = if have_rsvg {
            seam_count(&render_rsvg(&svg, size)?, size).to_string()
        } else {
            "-".into()
        };
        say!("| {size} | {} | {ours} | {theirs} |", size % GRID_PX);
    }
    say!("\n`snap26({}) = {}`", 1152, snap26(1152));

    // ---- where do they differ? ----
    //
    // A raw differing-pixel count cannot distinguish "different antialiasing
    // gamma on a piece outline", which is invisible, from "a glyph is missing or
    // shifted", which is fatal. Two measures that can:
    //
    //   structural — a differing pixel whose 3x3 neighbourhood in the other
    //                image contains nothing within tolerance. AA differences
    //                always have a near match one pixel away; a missing glyph
    //                does not.
    //   box4       — both images mean-downsampled 4x, then compared. AA washes
    //                out under downsampling; structure does not.
    if have_rsvg {
        say!("\n### Where the differences are\n");
        say!("AA gamma differs between any two rasterisers, so the raw count above is the wrong");
        say!("question. These two are the right ones.\n");
        say!("| case | structural (no 3x3 match) | box4 max delta | box4 differing >2 |");
        say!("|---|---|---|---|");
        for (name, fen, last, flip) in cases {
            let svg = board_svg(fen, *last, *flip, px)?;
            let a = render_resvg(&svg, px)?;
            let b = render_rsvg(&svg, px)?;
            let structural = structural_diff(&a, &b, px, 6);
            let (bmax, bdiff, btotal) = box4_diff(&a, &b, px);
            say!(
                "| {name} | {structural} ({:.4}%) | {bmax} | {bdiff} ({:.4}%) |",
                structural as f64 / (px * px) as f64 * 100.0,
                bdiff as f64 / btotal as f64 * 100.0,
            );
        }
        // And dump one case so a human can look at it, because a number cannot
        // settle "does it look right".
        let (name, fen, last, flip) = cases[2];
        let svg = board_svg(fen, last, flip, 390)?;
        let a = render_resvg(&svg, 390)?;
        let b = render_rsvg(&svg, 390)?;
        write_png("docs/f6-resvg.png", &a, 390)?;
        write_png("docs/f6-rsvg.png", &b, 390)?;
        write_png("docs/f6-diff.png", &amplified_diff(&a, &b), 390)?;
        say!(
            "\nDumped `{name}` at 390px to `docs/f6-{{resvg,rsvg,diff}}.png`. The diff is amplified 8x."
        );
    }

    let out = Path::new("docs/probe-f6.md");
    std::fs::write(out, &report).with_context(|| format!("write {}", out.display()))?;
    println!("\nwrote {}", out.display());
    Ok(())
}

/// Differing pixels that have no near match anywhere in the other image's 3x3
/// neighbourhood. An antialiasing disagreement always has one; a missing,
/// shifted or wrongly-filled glyph does not.
fn structural_diff(a: &[u8], b: &[u8], size: u32, tol: u8) -> usize {
    let at = |img: &[u8], x: u32, y: u32| -> [u8; 3] {
        let i = ((y * size + x) * 4) as usize;
        [img[i], img[i + 1], img[i + 2]]
    };
    let mut n = 0;
    for y in 1..size - 1 {
        for x in 1..size - 1 {
            let p = at(a, x, y);
            let q = at(b, x, y);
            if (0..3).map(|i| p[i].abs_diff(q[i])).max().unwrap() <= tol {
                continue;
            }
            let matched = (y - 1..=y + 1).any(|ny| {
                (x - 1..=x + 1).any(|nx| {
                    let r = at(b, nx, ny);
                    (0..3).map(|i| p[i].abs_diff(r[i])).max().unwrap() <= tol
                })
            });
            if !matched {
                n += 1;
            }
        }
    }
    n
}

/// Mean-downsample both images 4x and compare. Antialiasing differences average
/// away; a structural difference survives.
fn box4_diff(a: &[u8], b: &[u8], size: u32) -> (u8, usize, usize) {
    let small = size / 4;
    let mean = |img: &[u8], bx: u32, by: u32, c: usize| -> u16 {
        let mut s = 0u32;
        for dy in 0..4 {
            for dx in 0..4 {
                let i = (((by * 4 + dy) * size + bx * 4 + dx) * 4) as usize + c;
                s += img[i] as u32;
            }
        }
        (s / 16) as u16
    };
    let mut max = 0u8;
    let mut diff = 0usize;
    for by in 0..small {
        for bx in 0..small {
            let d = (0..3)
                .map(|c| (mean(a, bx, by, c) as i32 - mean(b, bx, by, c) as i32).unsigned_abs() as u8)
                .max()
                .unwrap();
            max = max.max(d);
            if d > 2 {
                diff += 1;
            }
        }
    }
    (max, diff, (small * small) as usize)
}

/// A visual diff: per-channel absolute difference, amplified 8x and clamped, so a
/// 4/255 antialiasing wobble is visible as dark grey and a structural error is
/// a solid blob.
fn amplified_diff(a: &[u8], b: &[u8]) -> Vec<u8> {
    a.chunks_exact(4)
        .zip(b.chunks_exact(4))
        .flat_map(|(p, q)| {
            let d: Vec<u8> = (0..3)
                .map(|i| p[i].abs_diff(q[i]).saturating_mul(8))
                .collect();
            [d[0], d[1], d[2], 255]
        })
        .collect()
}

fn write_png(path: &str, rgba: &[u8], size: u32) -> Result<()> {
    let file = std::fs::File::create(path).with_context(|| format!("create {path}"))?;
    let mut enc = png::Encoder::new(std::io::BufWriter::new(file), size, size);
    enc.set_color(png::ColorType::Rgba);
    enc.set_depth(png::BitDepth::Eight);
    enc.write_header()?.write_image_data(rgba)?;
    Ok(())
}

fn snap26(px: u32) -> u32 {
    (px - px % GRID_PX).max(GRID_PX)
}

/// Count pixels on the central scanline, inside the margin, that are neither
/// square colour. A blended edge pixel is a seam.
fn seam_count(rgba: &[u8], size: u32) -> usize {
    // The margin is 15 of 390 units on each side.
    let margin = (15.0 / 390.0 * size as f64).ceil() as u32;
    let y = size / 2;
    let row = &rgba[(y * size * 4) as usize..((y + 1) * size * 4) as usize];
    (margin..size - margin)
        .filter(|x| {
            let p = &row[(*x * 4) as usize..(*x * 4 + 3) as usize];
            p != SQ_LIGHT && p != SQ_DARK
        })
        .count()
}

/// Generate the board SVG with the *existing* python-chess, so the fidelity
/// comparison is about rasterisers and nothing else. Mirrors the arguments at
/// `scripts/dash/sixel.py::render`.
fn board_svg(fen: &str, last: Option<&str>, flip: bool, px: u32) -> Result<String> {
    // r##, not r#: the colour literals contain `"#`, which would close a
    // single-hash raw string right in the middle of the palette.
    let script = r##"
import sys, json, chess, chess.svg
fen, last, flip, px = sys.argv[1], sys.argv[2], sys.argv[3] == "1", int(sys.argv[4])
b = chess.Board(fen)
mv = chess.Move.from_uci(last) if last else None
sys.stdout.write(chess.svg.board(
    b,
    orientation=chess.BLACK if flip else chess.WHITE,
    lastmove=mv,
    check=b.king(b.turn) if b.is_check() else None,
    size=px, coordinates=True,
    colors={"square light": "#f0d9b5", "square dark": "#b58863",
            "square light lastmove": "#cdd26a", "square dark lastmove": "#aaa23a",
            "margin": "#2b2724", "coord": "#e5e0d5"},
))
"##;
    let out = Command::new("/home/nomad/dev/active/chess-gpu/.venv/bin/python")
        .args(["-c", script, fen, last.unwrap_or(""), if flip { "1" } else { "0" }])
        .arg(px.to_string())
        .output()
        .context("spawn python-chess to generate the reference SVG")?;
    if !out.status.success() {
        bail!("python-chess svg failed: {}", String::from_utf8_lossy(&out.stderr));
    }
    Ok(String::from_utf8(out.stdout)?)
}

/// The candidate path: usvg parse, resvg render, tiny-skia pixmap.
fn render_resvg(svg: &str, px: u32) -> Result<Vec<u8>> {
    use resvg::tiny_skia;
    use resvg::usvg;

    let opt = usvg::Options::default();
    let tree = usvg::Tree::from_str(svg, &opt).context("usvg parse")?;
    let mut pixmap = tiny_skia::Pixmap::new(px, px).context("allocate pixmap")?;
    let scale = px as f32 / tree.size().width();
    resvg::render(
        &tree,
        tiny_skia::Transform::from_scale(scale, scale),
        &mut pixmap.as_mut(),
    );
    // Demultiplied, because the sixel quantiser and any pixel comparison want
    // straight RGBA. On a fully opaque board this is a no-op, but the margin is
    // drawn as a stroke rather than a fill, so do not assume opacity.
    Ok(pixmap.take_demultiplied())
}

/// The incumbent path, for comparison only.
fn render_rsvg(svg: &str, px: u32) -> Result<Vec<u8>> {
    let mut child = Command::new("rsvg-convert")
        .args(["-w", &px.to_string(), "-h", &px.to_string(), "-f", "png"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .context("spawn rsvg-convert")?;
    child.stdin.take().unwrap().write_all(svg.as_bytes())?;
    let out = child.wait_with_output()?;
    if !out.status.success() {
        bail!("rsvg-convert failed: {}", String::from_utf8_lossy(&out.stderr));
    }
    decode_png_rgba(&out.stdout)
}

fn decode_png_rgba(bytes: &[u8]) -> Result<Vec<u8>> {
    let decoder = png::Decoder::new(std::io::Cursor::new(bytes));
    let mut reader = decoder.read_info().context("png read_info")?;
    let mut buf = vec![0; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf)?;
    buf.truncate(info.buffer_size());
    match info.color_type {
        png::ColorType::Rgba => Ok(buf),
        png::ColorType::Rgb => Ok(buf
            .chunks_exact(3)
            .flat_map(|p| [p[0], p[1], p[2], 255])
            .collect()),
        other => bail!("unexpected png colour type {other:?}"),
    }
}

fn which(bin: &str) -> bool {
    Command::new("sh")
        .args(["-c", &format!("command -v {bin} >/dev/null 2>&1")])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}
