#!/usr/bin/env python
"""Regenerate `sprites.py` from the cburnett piece set.

    scripts/dash/make_sprites.py            # rewrites scripts/dash/sprites.py

cburnett is the set lichess draws by default, so rasterising it is how the
board here ends up identical in *shape* to the one on the website rather than
merely chess-shaped. The SVGs are not downloaded: `python-chess` already ships
them (`chess.svg.PIECES`), same artwork, CC BY-SA, already a dependency.

## What comes out

Two bytes per pixel, luminance and alpha, per piece per size.

Luminance rather than colour because cburnett is two-tone by construction: a
white piece is white fill with black outline, a black piece is black fill with
white detail lines. Keeping the tone lets the renderer substitute any two ink
colours it likes, which is what keeps the board in the desktop palette while
the artwork stays lichess's. Alpha is kept at full resolution because it is
the antialiasing, and antialiasing is most of what makes a 16x16 piece read as
a piece rather than as a blob.

## Why it is generated ahead of time and checked in

The dashboard must not depend on `rsvg-convert` and ImageMagick being
installed to draw a board. They are needed here, once, by whoever changes the
artwork; `sprites.py` is plain data with no imports beyond base64.
"""

from __future__ import annotations

import base64
import subprocess
import sys
import textwrap
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import chess.svg

# Sizes are square-in-pixels, and each must match a `board.SCALES` entry:
# a scale of (cells_wide, cells_tall) draws cells_wide x cells_tall*2 pixels.
# Below 12 pixels cburnett stops being legible -- the king and queen
# collapse into two blobs -- so smaller boards use font glyphs instead
# and there is no point generating sprites they will never ask for.
SIZES = (12, 16, 24, 32, 40)
SYMBOLS = "KQRBNPkqrbnp"
VIEWBOX = 45          # cburnett's own coordinate system


def rasterise(symbol: str, size: int) -> bytes:
    """One piece at one size, as raw RGBA."""
    svg = (
        '<svg xmlns="http://www.w3.org/2000/svg" '
        'xmlns:xlink="http://www.w3.org/1999/xlink" '
        f'viewBox="0 0 {VIEWBOX} {VIEWBOX}" width="{VIEWBOX}" height="{VIEWBOX}">'
        + chess.svg.PIECES[symbol] + "</svg>"
    )
    png = subprocess.run(
        ["rsvg-convert", "-w", str(size), "-h", str(size), "-f", "png"],
        input=svg.encode(), capture_output=True, check=True,
    ).stdout
    raw = subprocess.run(
        ["magick", "png:-", "-depth", "8", "RGBA:-"],
        input=png, capture_output=True, check=True,
    ).stdout
    if len(raw) != size * size * 4:
        raise RuntimeError(f"{symbol}@{size}: got {len(raw)} bytes, want {size*size*4}")
    return raw


def to_tone_alpha(raw: bytes, size: int) -> bytes:
    """RGBA -> two bytes per pixel: luminance, alpha."""
    out = bytearray()
    for i in range(size * size):
        r, g, b, a = raw[i * 4: i * 4 + 4]
        out.append(int(0.299 * r + 0.587 * g + 0.114 * b))
        out.append(a)
    return bytes(out)


def main() -> None:
    blocks = {}
    for size in SIZES:
        for sym in SYMBOLS:
            blocks[(size, sym)] = to_tone_alpha(rasterise(sym, size), size)
            print(f"  {sym}@{size}", file=sys.stderr)

    lines = [
        '"""cburnett piece sprites. GENERATED by make_sprites.py -- do not edit.',
        "",
        "Two bytes per pixel, row major from the top left: luminance then alpha.",
        "Luminance 255 is the piece's light ink (a white piece's fill, a black",
        "piece's detail lines) and 0 is its dark ink; the renderer picks what",
        "those two inks actually are. Alpha is coverage against the square.",
        '"""',
        "",
        "import base64",
        "",
        "SIZES = " + repr(tuple(SIZES)),
        "",
        "_B64 = {",
    ]
    for (size, sym), data in blocks.items():
        b64 = base64.b64encode(data).decode()
        wrapped = textwrap.wrap(b64, 88)
        lines.append(f'    ({size}, {sym!r}): (')
        lines += [f'        "{chunk}"' for chunk in wrapped]
        lines.append("    ),")
    lines += [
        "}",
        "",
        "# Decoded once at import: 12 pieces x 3 sizes is a few tens of KB.",
        "SPRITES = {k: base64.b64decode(\"\".join(v)) for k, v in _B64.items()}",
        "",
    ]
    out = Path(__file__).with_name("sprites.py")
    out.write_text("\n".join(lines))
    print(f"wrote {out} ({out.stat().st_size} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
