[package]
name = "sf-term"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow    = { workspace = true }
base64    = { workspace = true }
crossterm = { workspace = true }
icy_sixel = { workspace = true }
ratatui   = { workspace = true }
sf-board  = { workspace = true }
sf-layout = { workspace = true }
tracing   = { workspace = true }
