#!/usr/bin/env python3
"""Lift the cburnett artwork out of python-chess into a Rust source file.

Run from `dashboard/`:

    ../.venv/bin/python xtask/codegen_cburnett.py > crates/sf-board/src/cburnett.rs

Why a generator rather than a hand-port: CLAUDE.md's own rule is "when porting a
reference implementation, exec the original and diff against it rather than
reading it carefully and reimplementing". The path data here is thousands of
bezier coordinates; a transcription error would be a subtly wrong knight that no
test would notice. So the artwork is extracted mechanically, checked in, and then
`sf-board`'s own test diffs the SVG *string* it assembles against python-chess's
own output over a couple of hundred positions.

The pieces are Colin M.L. Burnett's, triple-licensed GFDL / BSD / GPL. We take
the BSD arm and carry the attribution, which python-chess's `svg.py` itself does
not include -- so copying that file would not have carried it either.
"""

import chess.svg

def rust_str(s: str) -> str:
    # Raw strings with enough hashes to survive any `"#` inside the path data.
    n = 1
    while ('"' + '#' * n) in s:
        n += 1
    hashes = '#' * n
    return f'r{hashes}"{s}"{hashes}'

print('''//! GENERATED by `xtask/codegen_cburnett.py`. Do not edit by hand.
//!
//! The cburnett piece set and coordinate glyphs, lifted verbatim from
//! python-chess so that the board this dashboard draws is byte-identical to the
//! one lichess draws. Both are the same artwork.
//!
//! Artwork by Colin M.L. Burnett, used under the BSD arm of its GFDL/BSD/GPL
//! triple licence. The coordinate labels are `<path>` outlines rather than
//! `<text>`, which is the reason `resvg` needs no font machinery at all and the
//! binary carries no fontconfig dependency.
//!
//! Regenerate with:
//!     ../.venv/bin/python xtask/codegen_cburnett.py > crates/sf-board/src/cburnett.rs

/// One 45-unit square.
pub const SQUARE_SIZE: u32 = 45;

/// The margin `board()` uses when coordinates are drawn. Note this is NOT
/// python-chess's module-level `MARGIN` constant (20), which is used only as the
/// denominator of the coordinate glyph scale factor. Conflating the two is an easy
/// mistake: `board()` computes `margin = 15 if coordinates else 0`.
pub const COORD_MARGIN: u32 = 15;

/// The denominator in the glyph scale factor, `margin / GLYPH_MARGIN`.
pub const GLYPH_MARGIN: u32 = 20;
''')

print("/// A piece's `<g>` element, keyed by FEN symbol.")
print("pub fn piece(symbol: char) -> Option<&'static str> {")
print("    Some(match symbol {")
for k in sorted(chess.svg.PIECES.keys()):
    print(f"        {k!r} => {rust_str(chess.svg.PIECES[k])},")
print("        _ => return None,")
print("    })")
print("}\n")

print("/// A coordinate label's `<path>`, keyed by the character drawn.")
print("pub fn coord(c: char) -> Option<&'static str> {")
print("    Some(match c {")
for k in sorted(chess.svg.COORDS.keys()):
    print(f"        {k!r} => {rust_str(chess.svg.COORDS[k])},")
print("        _ => return None,")
print("    })")
print("}\n")

print("/// The `xx` marker, for squares marked as attacked.")
print(f"pub const XX: &str = {rust_str(chess.svg.XX)};\n")

print("/// The radial gradient the check indicator is painted with.")
print(f"pub const CHECK_GRADIENT: &str = {rust_str(chess.svg.CHECK_GRADIENT)};\n")

print("/// Every symbol we have artwork for, for the completeness test.")
syms = "".join(sorted(chess.svg.PIECES.keys()))
print(f'pub const PIECE_SYMBOLS: &str = "{syms}";')
coords = "".join(sorted(chess.svg.COORDS.keys()))
print(f'pub const COORD_CHARS: &str = "{coords}";')
